export const regionsInGhana = [
  { label: 'Ahafo', value: 'ahafo' },
  { label: 'Ashanti', value: 'ashanti' },
  { label: 'Bono', value: 'bono' },
  { label: 'Bono East', value: 'bono-east' },
  { label: 'Central', value: 'central' },
  { label: 'Eastern', value: 'eastern' },
  { label: 'Greater Accra', value: 'greater-accra' },
  { label: 'North East', value: 'north-east' },
  { label: 'Northern', value: 'northern' },
  { label: 'Oti', value: 'oti' },
  { label: 'Savannah', value: 'savannah' },
  { label: 'Upper East', value: 'upper-east' },
  { label: 'Upper West', value: 'upper-west' },
  { label: 'Volta', value: 'volta' },
  { label: 'Western', value: 'western' },
  { label: 'Western North', value: 'western-north' },
];
